<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style/theme/stylesheet.css">
    <title>Install</title>
</head>
<?php
    // DO NOT EDIT THIS FILE
	// - This is Database configurement, one-time install -
	
	$fields           = true;
	$created_database = false;
	$error;

	if (!isset($_POST['user']))
		$fields = false;
	if (!isset($_POST['host']))
		$fields = false;
	if (!isset($_POST['password']))
		$fields = false;

	function delTree($dir) {
		$files = array_diff(scandir($dir), array('.','..'));
			foreach ($files as $file) {
			(is_dir("$dir/$file")) ? delTree("$dir/$file") : unlink("$dir/$file");
			}
			return rmdir($dir);
		} 

	if ($fields)
	{
		$DB_HOST   = $_POST['host'];
		$DB_USER   = $_POST['user'];
		$DB_PASS   = $_POST['password'];
		try 
		{
			$MySQL = new PDO("mysql:host=$DB_HOST;", $DB_USER, $DB_PASS, array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));
			$sql = file_get_contents('install/create-database.sql');
			$MySQL->exec($sql);
			$created_database = true;
			
		}
		
		catch (Exception $e) {
			echo '<b>Could not create database:</b>\n\n ',  $e->getMessage(), "\n";
		}

		if ($created_database) {
			if (is_dir('configs'))
			{

					$file = fopen('configs/config.php', 'a');
					echo "<h1>yes<";
					$DB_CONFIG =
					'
					// Database Configs
					$DB_HOST   = \''.$DB_HOST.'\';
					$DB_NAME   = \'newsfeed_database\';
					$DB_USER   = \''.$DB_USER.'\';
					$DB_PASS   = \''.$DB_PASS.'\';
				
					';
					fputs($file, $DB_CONFIG);
					fclose($file);
				
			} else  die('Config file not found.');

			if (is_dir('install'))
			{
				delTree('install');
				rename ("index.php", "temp2.php");
				rename ("temp.php", "index.php");
				unlink ("temp2.php");
				header ('Location: index.php');
			}
			else die ('could not find install folder.');
		}
	} else {$error = "You have to enter your Database connection credentials.";}
	
?>
<body>
	<div id="install_box">
		<form action="index.php" method="POST" class="holder">
			<p>Hostname:</p><input type="text" name="host">
			<p>User:</p><input type="text" name="user">
			<p>Password:</p><input type="text" name="password">
			<input type="submit" value="Install Database"><br><br><?=$error?>
		</form>
	</div>
</body>
</html>
