<?php
    // DO NOT EDIT THIS FILE
	// - This is Database configurement, one-time install -

	$fields           = true;
	$created_database = false;
	$error[] = '';
	session_start();

	if (empty($_POST['user']))
	{
		$error[] = "You need to specify the <font color='green'>username</font> for your database login.<br>";
		$fields = false;
	}
	if (empty($_POST['host']))
	{
		$error[] = "You need to specify the <font color='purple'>hostname</font> for your database login.<br>";
				$fields = false;
	}

	function delTree($dir) {
		$files = array_diff(scandir($dir), array('.','..'));
			foreach ($files as $file) {
			(is_dir("$dir/$file")) ? delTree("$dir/$file") : unlink("$dir/$file");
			}
			return rmdir($dir);
		}

	if ($fields)
	{
		$DB_HOST   = trim($_POST['host']);
		$DB_USER   = trim($_POST['user']);
		$DB_PASS   = trim($_POST['password']);
		try
		{
			$MySQL = new PDO("mysql:host=$DB_HOST;", $DB_USER, $DB_PASS, array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));
			$sql = file_get_contents('install/create-database.sql');
			$MySQL->exec($sql);
			$created_database = true;

		}

		catch (Exception $e) {
			$error[] = '<b>Could not create database:</b><br>'.  $e->getMessage(). '<br>';
		}

		if ($created_database) {
			if (is_dir('configs'))
			{

					$file = fopen('configs/config.php', 'a');
					$DB_CONFIG =
					'
					// Database Configs
					$DB_HOST   = \''.$DB_HOST.'\';
					$DB_NAME   = \'newsfeed_database\';
					$DB_USER   = \''.$DB_USER.'\';
					$DB_PASS   = \''.$DB_PASS.'\';

					';
					fputs($file, $DB_CONFIG);
					fclose($file);

			} else  die('Config file not found.');

			if (is_dir('install'))
			{
				delTree('install');
				rename ("index.php", "temp2.php");
				rename ("temp.php", "index.php");
				unlink ("temp2.php");

				// HackFix session bug
				$Query = $MySQL->prepare('SELECT * FROM posts ORDER BY ID DESC');
				$Query->execute();
				$_SESSION['Results'] = $Query->fetchAll();
				// - End Hackfix

				header ('Location: index.php');
			}
			else die ('could not find install folder.');
		}
	}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style/theme/stylesheet.css">
    <title>Install</title>
</head>
<body>
	<div id="install_box">
		<form action="index.php" method="POST" class="holder">
			<p>Hostname:</p><input type="text" name="host">
			<p>User:</p><input type="text" name="user">
			<p>Password:</p><input type="text" name="password">
			<input type="submit" name="enter" value="Install Database"><br><br>
			<?php
			if (isset($_POST['enter']))
			{
				foreach ($error as $r)
				 echo $r;
			}?>
		</form>
	</div>
</body>
</html>
